all: pdf

pdf: exploring_the_world_of_lucid_dreaming.tex
	pdflatex exploring_the_world_of_lucid_dreaming.tex

clean:
	rm exploring_the_world_of_lucid_dreaming.aux exploring_the_world_of_lucid_dreaming.log exploring_the_world_of_lucid_dreaming.toc